# FreeBSD support, duplicates the efforts of the FreeBSD port
#
include makefile.unix

USE_UPNP := 0

# Added so Boost and Berkley DB can be found
CXXFLAGS +=	-I/usr/local/include -I/usr/local/include/db47
CXXFLAGS +=	-L/usr/local/lib -L/usr/local/lib/db47
CXXFLAGS +=	-Wno-invalid-offsetof
CXXFLAGS +=	-DBSD

# remove -l dl, not required?
LIBS := $(subst -l dl,,$(LIBS))
